//
// SwiftUI Tokens – Auto generated by Style Dictionary
//

import SwiftUI

public enum DesignTokens {
    public enum Colors {
        public enum Base {
            public static let white = "rgba(255, 255, 255, 1)"
            public static let black = "rgba(0, 0, 0, 1)"
            public static let transparent = "rgba(255, 255, 255, 0)"
        }
        public enum Gray {
            public enum _light {
                public enum mode_ {
                    public static let _25 = "rgba(253, 253, 252, 1)"
                    public static let _50 = "rgba(247, 246, 245, 1)"
                    public static let _100 = "rgba(240, 239, 237, 1)"
                    public static let _200 = "rgba(228, 227, 225, 1)"
                    public static let _300 = "rgba(215, 211, 208, 1)"
                    public static let _400 = "rgba(169, 162, 157, 1)"
                    public static let _500 = "rgba(121, 113, 107, 1)"
                    public static let _600 = "rgba(87, 83, 78, 1)"
                    public static let _700 = "rgba(68, 64, 60, 1)"
                    public static let _800 = "rgba(41, 37, 36, 1)"
                    public static let _900 = "rgba(21, 21, 21, 1)"
                    public static let _950 = "rgba(21, 21, 21, 1)"
                }
            }
            public enum _dark {
                public enum mode_ {
                    public static let _25 = "rgba(250, 250, 250, 1)"
                    public static let _50 = "rgba(247, 247, 247, 1)"
                    public static let _100 = "rgba(240, 240, 241, 1)"
                    public static let _200 = "rgba(236, 236, 237, 1)"
                    public static let _300 = "rgba(206, 207, 210, 1)"
                    public static let _400 = "rgba(148, 151, 156, 1)"
                    public static let _500 = "rgba(133, 136, 142, 1)"
                    public static let _600 = "rgba(97, 101, 108, 1)"
                    public static let _700 = "rgba(55, 58, 65, 1)"
                    public static let _800 = "rgba(34, 38, 47, 1)"
                    public static let _900 = "rgba(19, 22, 27, 1)"
                    public static let _950 = "rgba(12, 14, 18, 1)"
                }
                public enum mode {
                    public enum alpha_ {
                        public static let _25 = "rgba(255, 255, 255, 0.9800000190734863)"
                        public static let _50 = "rgba(255, 255, 255, 0.9599999785423279)"
                        public static let _100 = "rgba(255, 255, 255, 0.9399999976158142)"
                        public static let _200 = "rgba(255, 255, 255, 0.9200000166893005)"
                        public static let _300 = "rgba(255, 255, 255, 0.800000011920929)"
                        public static let _400 = "rgba(255, 255, 255, 0.5600000023841858)"
                        public static let _500 = "rgba(255, 255, 255, 0.5)"
                        public static let _600 = "rgba(255, 255, 255, 0.3499999940395355)"
                        public static let _700 = "rgba(255, 255, 255, 0.1599999964237213)"
                        public static let _800 = "rgba(255, 255, 255, 0.07999999821186066)"
                        public static let _900 = "rgba(255, 255, 255, 0.03999999910593033)"
                        public static let _950 = "rgba(255, 255, 255, 0)"
                    }
                }
            }
            public enum blue {
                public static let _25 = "rgba(252, 252, 253, 1)"
                public static let _50 = "rgba(248, 249, 252, 1)"
                public static let _100 = "rgba(234, 236, 245, 1)"
                public static let _200 = "rgba(213, 217, 235, 1)"
                public static let _300 = "rgba(179, 184, 219, 1)"
                public static let _400 = "rgba(113, 123, 188, 1)"
                public static let _500 = "rgba(78, 91, 166, 1)"
                public static let _600 = "rgba(62, 71, 132, 1)"
                public static let _700 = "rgba(54, 63, 114, 1)"
                public static let _800 = "rgba(41, 48, 86, 1)"
                public static let _900 = "rgba(16, 19, 35, 1)"
                public static let _950 = "rgba(13, 15, 28, 1)"
            }
            public enum cool {
                public static let _25 = "rgba(252, 252, 253, 1)"
                public static let _50 = "rgba(249, 249, 251, 1)"
                public static let _100 = "rgba(239, 241, 245, 1)"
                public static let _200 = "rgba(220, 223, 234, 1)"
                public static let _300 = "rgba(185, 192, 212, 1)"
                public static let _400 = "rgba(125, 137, 176, 1)"
                public static let _500 = "rgba(93, 107, 152, 1)"
                public static let _600 = "rgba(74, 85, 120, 1)"
                public static let _700 = "rgba(64, 73, 104, 1)"
                public static let _800 = "rgba(48, 55, 79, 1)"
                public static let _900 = "rgba(17, 19, 34, 1)"
                public static let _950 = "rgba(14, 16, 27, 1)"
            }
            public enum modern {
                public static let _25 = "rgba(252, 252, 253, 1)"
                public static let _50 = "rgba(248, 250, 252, 1)"
                public static let _100 = "rgba(238, 242, 246, 1)"
                public static let _200 = "rgba(227, 232, 239, 1)"
                public static let _300 = "rgba(205, 213, 223, 1)"
                public static let _400 = "rgba(154, 164, 178, 1)"
                public static let _500 = "rgba(105, 117, 134, 1)"
                public static let _600 = "rgba(75, 85, 101, 1)"
                public static let _700 = "rgba(54, 65, 82, 1)"
                public static let _800 = "rgba(32, 41, 57, 1)"
                public static let _900 = "rgba(18, 25, 38, 1)"
                public static let _950 = "rgba(13, 18, 28, 1)"
            }
            public enum neutral {
                public static let _25 = "rgba(252, 252, 253, 1)"
                public static let _50 = "rgba(249, 250, 251, 1)"
                public static let _100 = "rgba(243, 244, 246, 1)"
                public static let _200 = "rgba(229, 231, 235, 1)"
                public static let _300 = "rgba(210, 214, 219, 1)"
                public static let _400 = "rgba(157, 164, 174, 1)"
                public static let _500 = "rgba(108, 115, 127, 1)"
                public static let _600 = "rgba(77, 87, 97, 1)"
                public static let _700 = "rgba(56, 66, 80, 1)"
                public static let _800 = "rgba(31, 42, 55, 1)"
                public static let _900 = "rgba(17, 25, 39, 1)"
                public static let _950 = "rgba(13, 18, 28, 1)"
            }
            public enum iron {
                public static let _25 = "rgba(252, 252, 252, 1)"
                public static let _50 = "rgba(250, 250, 250, 1)"
                public static let _100 = "rgba(244, 244, 245, 1)"
                public static let _200 = "rgba(228, 228, 231, 1)"
                public static let _300 = "rgba(209, 209, 214, 1)"
                public static let _400 = "rgba(160, 160, 171, 1)"
                public static let _500 = "rgba(112, 112, 123, 1)"
                public static let _600 = "rgba(81, 82, 92, 1)"
                public static let _700 = "rgba(63, 63, 70, 1)"
                public static let _800 = "rgba(38, 39, 43, 1)"
                public static let _900 = "rgba(26, 26, 30, 1)"
                public static let _950 = "rgba(19, 19, 22, 1)"
            }
            public enum true_token {
                public static let _25 = "rgba(252, 252, 252, 1)"
                public static let _50 = "rgba(247, 247, 247, 1)"
                public static let _100 = "rgba(245, 245, 245, 1)"
                public static let _200 = "rgba(229, 229, 229, 1)"
                public static let _300 = "rgba(214, 214, 214, 1)"
                public static let _400 = "rgba(163, 163, 163, 1)"
                public static let _500 = "rgba(115, 115, 115, 1)"
                public static let _600 = "rgba(82, 82, 82, 1)"
                public static let _700 = "rgba(66, 66, 66, 1)"
                public static let _800 = "rgba(41, 41, 41, 1)"
                public static let _900 = "rgba(20, 20, 20, 1)"
                public static let _950 = "rgba(15, 15, 15, 1)"
            }
            public enum warm {
                public static let _25 = "rgba(253, 253, 252, 1)"
                public static let _50 = "rgba(250, 250, 249, 1)"
                public static let _100 = "rgba(245, 245, 244, 1)"
                public static let _200 = "rgba(231, 229, 228, 1)"
                public static let _300 = "rgba(215, 211, 208, 1)"
                public static let _400 = "rgba(169, 162, 157, 1)"
                public static let _500 = "rgba(121, 113, 107, 1)"
                public static let _600 = "rgba(87, 83, 78, 1)"
                public static let _700 = "rgba(68, 64, 60, 1)"
                public static let _800 = "rgba(41, 37, 36, 1)"
                public static let _900 = "rgba(28, 25, 23, 1)"
                public static let _950 = "rgba(23, 20, 18, 1)"
            }
        }
        public enum Brand {
            public static let _25 = "rgba(254, 248, 245, 1)"
            public static let _50 = "rgba(254, 244, 240, 1)"
            public static let _100 = "rgba(253, 224, 214, 1)"
            public static let _200 = "rgba(250, 194, 173, 1)"
            public static let _300 = "rgba(248, 163, 133, 1)"
            public static let _400 = "rgba(247, 133, 92, 1)"
            public static let _500 = "rgba(246, 117, 71, 1)"
            public static let _600 = "rgba(243, 102, 51, 1)"
            public static let _700 = "rgba(220, 62, 5, 1)"
            public static let _800 = "rgba(195, 55, 4, 1)"
            public static let _900 = "rgba(165, 50, 8, 1)"
            public static let _950 = "rgba(138, 37, 0, 1)"
        }
        public enum Error {
            public static let _25 = "rgba(255, 251, 250, 1)"
            public static let _50 = "rgba(254, 243, 242, 1)"
            public static let _100 = "rgba(254, 228, 226, 1)"
            public static let _200 = "rgba(254, 205, 202, 1)"
            public static let _300 = "rgba(253, 162, 155, 1)"
            public static let _400 = "rgba(249, 112, 102, 1)"
            public static let _500 = "rgba(240, 68, 56, 1)"
            public static let _600 = "rgba(200, 54, 41, 1)"
            public static let _700 = "rgba(180, 35, 24, 1)"
            public static let _800 = "rgba(145, 32, 24, 1)"
            public static let _900 = "rgba(122, 39, 26, 1)"
            public static let _950 = "rgba(85, 22, 12, 1)"
        }
        public enum Warning {
            public static let _25 = "rgba(255, 252, 245, 1)"
            public static let _50 = "rgba(255, 250, 235, 1)"
            public static let _100 = "rgba(254, 240, 199, 1)"
            public static let _200 = "rgba(254, 223, 137, 1)"
            public static let _300 = "rgba(254, 200, 75, 1)"
            public static let _400 = "rgba(255, 199, 9, 1)"
            public static let _500 = "rgba(255, 199, 9, 1)"
            public static let _600 = "rgba(255, 199, 9, 1)"
            public static let _700 = "rgba(255, 199, 9, 1)"
            public static let _800 = "rgba(255, 199, 9, 1)"
            public static let _900 = "rgba(255, 199, 9, 1)"
            public static let _950 = "rgba(255, 199, 9, 1)"
        }
        public enum Success {
            public static let _25 = "rgba(246, 254, 249, 1)"
            public static let _50 = "rgba(236, 253, 243, 1)"
            public static let _100 = "rgba(220, 250, 230, 1)"
            public static let _200 = "rgba(171, 239, 198, 1)"
            public static let _300 = "rgba(117, 224, 167, 1)"
            public static let _400 = "rgba(71, 205, 137, 1)"
            public static let _500 = "rgba(23, 178, 106, 1)"
            public static let _600 = "rgba(68, 132, 34, 1)"
            public static let _700 = "rgba(6, 118, 71, 1)"
            public static let _800 = "rgba(8, 93, 58, 1)"
            public static let _900 = "rgba(7, 77, 49, 1)"
            public static let _950 = "rgba(5, 51, 33, 1)"
        }
        public enum Moss {
            public static let _25 = "rgba(250, 253, 247, 1)"
            public static let _50 = "rgba(245, 251, 238, 1)"
            public static let _100 = "rgba(230, 244, 215, 1)"
            public static let _200 = "rgba(206, 234, 176, 1)"
            public static let _300 = "rgba(172, 220, 121, 1)"
            public static let _400 = "rgba(134, 203, 60, 1)"
            public static let _500 = "rgba(102, 159, 42, 1)"
            public static let _600 = "rgba(79, 122, 33, 1)"
            public static let _700 = "rgba(63, 98, 26, 1)"
            public static let _800 = "rgba(51, 80, 21, 1)"
            public static let _900 = "rgba(43, 66, 18, 1)"
            public static let _950 = "rgba(26, 40, 11, 1)"
        }
        public enum Green {
            public static let _25 = "rgba(246, 254, 249, 1)"
            public static let _50 = "rgba(237, 252, 242, 1)"
            public static let _100 = "rgba(211, 248, 223, 1)"
            public static let _200 = "rgba(170, 240, 196, 1)"
            public static let _300 = "rgba(115, 226, 163, 1)"
            public static let _400 = "rgba(60, 203, 127, 1)"
            public static let _500 = "rgba(22, 179, 100, 1)"
            public static let _600 = "rgba(9, 146, 80, 1)"
            public static let _700 = "rgba(8, 116, 67, 1)"
            public static let _800 = "rgba(9, 92, 55, 1)"
            public static let _900 = "rgba(8, 76, 46, 1)"
            public static let _950 = "rgba(5, 46, 28, 1)"
            public enum light {
                public static let _25 = "rgba(250, 254, 245, 1)"
                public static let _50 = "rgba(243, 254, 231, 1)"
                public static let _100 = "rgba(227, 251, 204, 1)"
                public static let _200 = "rgba(208, 248, 171, 1)"
                public static let _300 = "rgba(166, 239, 103, 1)"
                public static let _400 = "rgba(133, 225, 58, 1)"
                public static let _500 = "rgba(102, 198, 28, 1)"
                public static let _600 = "rgba(76, 163, 13, 1)"
                public static let _700 = "rgba(59, 124, 15, 1)"
                public static let _800 = "rgba(50, 98, 18, 1)"
                public static let _900 = "rgba(43, 83, 20, 1)"
                public static let _950 = "rgba(21, 41, 10, 1)"
            }
        }
        public enum Teal {
            public static let _25 = "rgba(246, 254, 252, 1)"
            public static let _50 = "rgba(240, 253, 249, 1)"
            public static let _100 = "rgba(204, 251, 239, 1)"
            public static let _200 = "rgba(153, 246, 224, 1)"
            public static let _300 = "rgba(95, 233, 208, 1)"
            public static let _400 = "rgba(46, 211, 183, 1)"
            public static let _500 = "rgba(21, 183, 158, 1)"
            public static let _600 = "rgba(14, 147, 132, 1)"
            public static let _700 = "rgba(16, 117, 105, 1)"
            public static let _800 = "rgba(18, 93, 86, 1)"
            public static let _900 = "rgba(19, 78, 72, 1)"
            public static let _950 = "rgba(10, 41, 38, 1)"
        }
        public enum Cyan {
            public static let _25 = "rgba(245, 254, 255, 1)"
            public static let _50 = "rgba(236, 253, 255, 1)"
            public static let _100 = "rgba(207, 249, 254, 1)"
            public static let _200 = "rgba(165, 240, 252, 1)"
            public static let _300 = "rgba(103, 227, 249, 1)"
            public static let _400 = "rgba(34, 204, 238, 1)"
            public static let _500 = "rgba(6, 174, 212, 1)"
            public static let _600 = "rgba(8, 138, 178, 1)"
            public static let _700 = "rgba(14, 112, 144, 1)"
            public static let _800 = "rgba(21, 91, 117, 1)"
            public static let _900 = "rgba(22, 76, 99, 1)"
            public static let _950 = "rgba(13, 45, 58, 1)"
        }
        public enum Blue {
            public static let _25 = "rgba(245, 250, 255, 1)"
            public static let _50 = "rgba(239, 248, 255, 1)"
            public static let _100 = "rgba(209, 233, 255, 1)"
            public static let _200 = "rgba(178, 221, 255, 1)"
            public static let _300 = "rgba(132, 202, 255, 1)"
            public static let _400 = "rgba(83, 177, 253, 1)"
            public static let _500 = "rgba(46, 144, 250, 1)"
            public static let _600 = "rgba(21, 112, 239, 1)"
            public static let _700 = "rgba(23, 92, 211, 1)"
            public static let _800 = "rgba(24, 73, 169, 1)"
            public static let _900 = "rgba(25, 65, 133, 1)"
            public static let _950 = "rgba(16, 42, 86, 1)"
            public enum light {
                public static let _25 = "rgba(245, 251, 255, 1)"
                public static let _50 = "rgba(240, 249, 255, 1)"
                public static let _100 = "rgba(224, 242, 254, 1)"
                public static let _200 = "rgba(185, 230, 254, 1)"
                public static let _300 = "rgba(124, 212, 253, 1)"
                public static let _400 = "rgba(54, 191, 250, 1)"
                public static let _500 = "rgba(11, 165, 236, 1)"
                public static let _600 = "rgba(0, 134, 201, 1)"
                public static let _700 = "rgba(2, 106, 162, 1)"
                public static let _800 = "rgba(6, 89, 134, 1)"
                public static let _900 = "rgba(11, 74, 111, 1)"
                public static let _950 = "rgba(6, 44, 65, 1)"
            }
            public enum dark {
                public static let _25 = "rgba(245, 248, 255, 1)"
                public static let _50 = "rgba(239, 244, 255, 1)"
                public static let _100 = "rgba(209, 224, 255, 1)"
                public static let _200 = "rgba(178, 204, 255, 1)"
                public static let _300 = "rgba(132, 173, 255, 1)"
                public static let _400 = "rgba(82, 139, 255, 1)"
                public static let _500 = "rgba(41, 112, 255, 1)"
                public static let _600 = "rgba(21, 94, 239, 1)"
                public static let _700 = "rgba(0, 78, 235, 1)"
                public static let _800 = "rgba(0, 64, 193, 1)"
                public static let _900 = "rgba(0, 53, 158, 1)"
                public static let _950 = "rgba(0, 34, 102, 1)"
            }
        }
        public enum Indigo {
            public static let _25 = "rgba(245, 248, 255, 1)"
            public static let _50 = "rgba(238, 244, 255, 1)"
            public static let _100 = "rgba(224, 234, 255, 1)"
            public static let _200 = "rgba(199, 215, 254, 1)"
            public static let _300 = "rgba(164, 188, 253, 1)"
            public static let _400 = "rgba(128, 152, 249, 1)"
            public static let _500 = "rgba(97, 114, 243, 1)"
            public static let _600 = "rgba(68, 76, 231, 1)"
            public static let _700 = "rgba(53, 56, 205, 1)"
            public static let _800 = "rgba(45, 49, 166, 1)"
            public static let _900 = "rgba(45, 50, 130, 1)"
            public static let _950 = "rgba(31, 35, 91, 1)"
        }
        public enum Violet {
            public static let _25 = "rgba(251, 250, 255, 1)"
            public static let _50 = "rgba(245, 243, 255, 1)"
            public static let _100 = "rgba(236, 233, 254, 1)"
            public static let _200 = "rgba(221, 214, 254, 1)"
            public static let _300 = "rgba(195, 181, 253, 1)"
            public static let _400 = "rgba(164, 138, 251, 1)"
            public static let _500 = "rgba(135, 91, 247, 1)"
            public static let _600 = "rgba(120, 57, 238, 1)"
            public static let _700 = "rgba(105, 39, 218, 1)"
            public static let _800 = "rgba(87, 32, 183, 1)"
            public static let _900 = "rgba(73, 28, 150, 1)"
            public static let _950 = "rgba(46, 18, 94, 1)"
        }
        public enum Purple {
            public static let _25 = "rgba(250, 250, 255, 1)"
            public static let _50 = "rgba(244, 243, 255, 1)"
            public static let _100 = "rgba(235, 233, 254, 1)"
            public static let _200 = "rgba(217, 214, 254, 1)"
            public static let _300 = "rgba(189, 180, 254, 1)"
            public static let _400 = "rgba(155, 138, 251, 1)"
            public static let _500 = "rgba(122, 90, 248, 1)"
            public static let _600 = "rgba(105, 56, 239, 1)"
            public static let _700 = "rgba(89, 37, 220, 1)"
            public static let _800 = "rgba(74, 31, 184, 1)"
            public static let _900 = "rgba(62, 28, 150, 1)"
            public static let _950 = "rgba(39, 17, 95, 1)"
        }
        public enum Fuchsia {
            public static let _25 = "rgba(254, 250, 255, 1)"
            public static let _50 = "rgba(253, 244, 255, 1)"
            public static let _100 = "rgba(251, 232, 255, 1)"
            public static let _200 = "rgba(246, 208, 254, 1)"
            public static let _300 = "rgba(238, 170, 253, 1)"
            public static let _400 = "rgba(228, 120, 250, 1)"
            public static let _500 = "rgba(212, 68, 241, 1)"
            public static let _600 = "rgba(186, 36, 213, 1)"
            public static let _700 = "rgba(159, 26, 177, 1)"
            public static let _800 = "rgba(130, 24, 144, 1)"
            public static let _900 = "rgba(111, 24, 119, 1)"
            public static let _950 = "rgba(71, 16, 76, 1)"
        }
        public enum Pink {
            public static let _25 = "rgba(254, 246, 251, 1)"
            public static let _50 = "rgba(253, 242, 250, 1)"
            public static let _100 = "rgba(252, 231, 246, 1)"
            public static let _200 = "rgba(252, 206, 238, 1)"
            public static let _300 = "rgba(250, 167, 224, 1)"
            public static let _400 = "rgba(246, 112, 199, 1)"
            public static let _500 = "rgba(238, 70, 188, 1)"
            public static let _600 = "rgba(221, 37, 144, 1)"
            public static let _700 = "rgba(193, 21, 116, 1)"
            public static let _800 = "rgba(158, 22, 95, 1)"
            public static let _900 = "rgba(133, 22, 81, 1)"
            public static let _950 = "rgba(78, 13, 48, 1)"
        }
        public enum Ros_ {
            public static let _25 = "rgba(255, 245, 246, 1)"
            public static let _50 = "rgba(255, 241, 243, 1)"
            public static let _100 = "rgba(255, 228, 232, 1)"
            public static let _200 = "rgba(254, 205, 214, 1)"
            public static let _300 = "rgba(254, 163, 180, 1)"
            public static let _400 = "rgba(253, 111, 142, 1)"
            public static let _500 = "rgba(246, 61, 104, 1)"
            public static let _600 = "rgba(227, 27, 84, 1)"
            public static let _700 = "rgba(192, 16, 72, 1)"
            public static let _800 = "rgba(161, 16, 67, 1)"
            public static let _900 = "rgba(137, 18, 62, 1)"
            public static let _950 = "rgba(81, 11, 36, 1)"
        }
        public enum Orange {
            public static let _25 = "rgba(254, 250, 245, 1)"
            public static let _50 = "rgba(254, 246, 238, 1)"
            public static let _100 = "rgba(253, 234, 215, 1)"
            public static let _200 = "rgba(249, 219, 175, 1)"
            public static let _300 = "rgba(247, 178, 122, 1)"
            public static let _400 = "rgba(243, 135, 68, 1)"
            public static let _500 = "rgba(239, 104, 32, 1)"
            public static let _600 = "rgba(224, 79, 22, 1)"
            public static let _700 = "rgba(185, 56, 21, 1)"
            public static let _800 = "rgba(147, 47, 25, 1)"
            public static let _900 = "rgba(119, 41, 23, 1)"
            public static let _950 = "rgba(81, 28, 16, 1)"
            public enum dark {
                public static let _25 = "rgba(255, 249, 245, 1)"
                public static let _50 = "rgba(255, 244, 237, 1)"
                public static let _100 = "rgba(255, 230, 213, 1)"
                public static let _200 = "rgba(255, 214, 174, 1)"
                public static let _300 = "rgba(255, 156, 102, 1)"
                public static let _400 = "rgba(255, 105, 46, 1)"
                public static let _500 = "rgba(255, 68, 5, 1)"
                public static let _600 = "rgba(230, 46, 5, 1)"
                public static let _700 = "rgba(188, 27, 6, 1)"
                public static let _800 = "rgba(151, 24, 12, 1)"
                public static let _900 = "rgba(119, 26, 13, 1)"
                public static let _950 = "rgba(87, 19, 10, 1)"
            }
        }
        public enum Yellow {
            public static let _25 = "rgba(254, 253, 240, 1)"
            public static let _50 = "rgba(254, 251, 232, 1)"
            public static let _100 = "rgba(254, 247, 195, 1)"
            public static let _200 = "rgba(254, 238, 149, 1)"
            public static let _300 = "rgba(253, 226, 114, 1)"
            public static let _400 = "rgba(250, 197, 21, 1)"
            public static let _500 = "rgba(234, 170, 8, 1)"
            public static let _600 = "rgba(202, 133, 4, 1)"
            public static let _700 = "rgba(161, 92, 7, 1)"
            public static let _800 = "rgba(133, 74, 14, 1)"
            public static let _900 = "rgba(113, 59, 18, 1)"
            public static let _950 = "rgba(84, 44, 13, 1)"
        }
        public enum Text {
            public enum text_primary {
                public static let _900_ = "rgba(21, 21, 21, 1)"
            }
            public static let text_primary_on_brand = "rgba(255, 255, 255, 1)"
            public enum text_secondary {
                public static let _700_ = "rgba(68, 64, 60, 1)"
            }
            public static let text_secondary_hover = "rgba(21, 21, 21, 1)"
            public static let text_secondary_on_brand = "rgba(254, 248, 245, 1)"
            public enum text_tertiary {
                public static let _600_ = "rgba(87, 83, 78, 1)"
            }
            public static let text_tertiary_hover = "rgba(68, 64, 60, 1)"
            public static let text_tertiary_on_brand = "rgba(254, 248, 245, 1)"
            public enum text_quaternary {
                public static let _500_ = "rgba(121, 113, 107, 1)"
            }
            public static let text_quaternary_on_brand = "rgba(254, 248, 245, 1)"
            public static let text_white = "rgba(255, 255, 255, 1)"
            public static let text_disabled = "rgba(215, 211, 208, 1)"
            public static let text_placeholder = "rgba(169, 162, 157, 1)"
            public static let text_placeholder_subtle = "rgba(215, 211, 208, 1)"
            public enum text_brand_primary {
                public static let _900_ = "rgba(165, 50, 8, 1)"
            }
            public enum text_brand_secondary {
                public static let _700_ = "rgba(220, 62, 5, 1)"
            }
            public static let text_brand_secondary_hover = "rgba(195, 55, 4, 1)"
            public enum text_brand_tertiary {
                public static let _600_ = "rgba(243, 102, 51, 1)"
            }
            public static let text_brand_tertiary_alt = "rgba(243, 102, 51, 1)"
            public enum text_error_primary {
                public static let _600_ = "rgba(200, 54, 41, 1)"
            }
            public static let text_error_primary_hover = "rgba(180, 35, 24, 1)"
            public enum text_warning_primary {
                public static let _600_ = "rgba(255, 199, 9, 1)"
            }
            public enum text_success_primary {
                public static let _600_ = "rgba(68, 132, 34, 1)"
            }
        }
        public enum Border {
            public static let border_primary = "rgba(215, 211, 208, 1)"
            public static let border_secondary = "rgba(228, 227, 225, 1)"
            public static let border_secondary_alt = "rgba(0, 0, 0, 0.07999999821186066)"
            public static let border_tertiary = "rgba(240, 239, 237, 1)"
            public static let border_disabled = "rgba(215, 211, 208, 1)"
            public static let border_disabled_subtle = "rgba(228, 227, 225, 1)"
            public static let border_brand = "rgba(246, 117, 71, 1)"
            public static let border_brand_alt = "rgba(243, 102, 51, 1)"
            public static let border_error = "rgba(240, 68, 56, 1)"
            public static let border_error_subtle = "rgba(253, 162, 155, 1)"
        }
        public enum Foreground {
            public enum fg_primary {
                public static let _900_ = "rgba(21, 21, 21, 1)"
            }
            public enum fg_secondary {
                public static let _700_ = "rgba(68, 64, 60, 1)"
            }
            public static let fg_secondary_hover = "rgba(41, 37, 36, 1)"
            public enum fg_tertiary {
                public static let _600_ = "rgba(87, 83, 78, 1)"
            }
            public static let fg_tertiary_hover = "rgba(68, 64, 60, 1)"
            public enum fg_quaternary {
                public static let _400_ = "rgba(121, 113, 107, 1)"
            }
            public static let fg_quaternary_hover = "rgba(121, 113, 107, 1)"
            public static let fg_white = "rgba(255, 255, 255, 1)"
            public static let fg_disabled = "rgba(215, 211, 208, 1)"
            public static let fg_disabled_subtle = "rgba(228, 227, 225, 1)"
            public enum fg_brand_primary {
                public static let _600_ = "rgba(243, 102, 51, 1)"
            }
            public static let fg_brand_primary_alt = "rgba(243, 102, 51, 1)"
            public enum fg_brand_secondary {
                public static let _500_ = "rgba(246, 117, 71, 1)"
            }
            public static let fg_brand_secondary_alt = "rgba(246, 117, 71, 1)"
            public static let fg_brand_secondary_hover = "rgba(243, 102, 51, 1)"
            public static let fg_error_primary = "rgba(200, 54, 41, 1)"
            public static let fg_error_secondary = "rgba(240, 68, 56, 1)"
            public static let fg_warning_primary = "rgba(255, 199, 9, 1)"
            public static let fg_warning_secondary = "rgba(255, 199, 9, 1)"
            public static let fg_success_primary = "rgba(68, 132, 34, 1)"
            public static let fg_success_secondary = "rgba(23, 178, 106, 1)"
        }
        public enum Background {
            public static let bg_primary = "rgba(255, 255, 255, 1)"
            public static let bg_primary_alt = "rgba(255, 255, 255, 1)"
            public static let bg_primary_hover = "rgba(247, 246, 245, 1)"
            public static let bg_primary_solid = "rgba(21, 21, 21, 1)"
            public static let bg_secondary = "rgba(247, 246, 245, 1)"
            public static let bg_secondary_alt = "rgba(247, 246, 245, 1)"
            public static let bg_secondary_hover = "rgba(240, 239, 237, 1)"
            public static let bg_secondary_subtle = "rgba(253, 253, 252, 1)"
            public static let bg_secondary_solid = "rgba(87, 83, 78, 1)"
            public static let bg_tertiary = "rgba(240, 239, 237, 1)"
            public static let bg_quaternary = "rgba(228, 227, 225, 1)"
            public static let bg_active = "rgba(247, 246, 245, 1)"
            public static let bg_disabled = "rgba(240, 239, 237, 1)"
            public static let bg_disabled_subtle = "rgba(247, 246, 245, 1)"
            public static let bg_overlay = "rgba(228, 227, 225, 1)"
            public static let bg_brand_primary = "rgba(254, 244, 240, 1)"
            public static let bg_brand_primary_alt = "rgba(254, 244, 240, 1)"
            public static let bg_brand_secondary = "rgba(253, 224, 214, 1)"
            public static let bg_brand_solid = "rgba(243, 102, 51, 1)"
            public static let bg_brand_solid_hover = "rgba(220, 62, 5, 1)"
            public static let bg_brand_section = "rgba(243, 102, 51, 1)"
            public static let bg_brand_section_subtle = "rgba(220, 62, 5, 1)"
            public static let bg_error_primary = "rgba(254, 243, 242, 1)"
            public static let bg_error_secondary = "rgba(254, 228, 226, 1)"
            public static let bg_error_solid = "rgba(200, 54, 41, 1)"
            public static let bg_error_solid_hover = "rgba(180, 35, 24, 1)"
            public static let bg_warning_primary = "rgba(255, 250, 235, 1)"
            public static let bg_warning_secondary = "rgba(254, 240, 199, 1)"
            public static let bg_warning_solid = "rgba(255, 199, 9, 1)"
            public static let bg_success_primary = "rgba(236, 253, 243, 1)"
            public static let bg_success_secondary = "rgba(220, 250, 230, 1)"
            public static let bg_success_solid = "rgba(68, 132, 34, 1)"
        }
        public enum Effects {
            public enum Focus {
                public enum rings {
                    public static let focus_ring = "rgba(21, 21, 21, 1)"
                    public static let focus_ring_error = "rgba(240, 68, 56, 1)"
                }
            }
            public enum Shadows {
                public static let shadow_xs = "rgba(10, 13, 18, 0.05000000074505806)"
                public static let shadow_sm_01 = "rgba(10, 13, 18, 0.10000000149011612)"
                public static let shadow_sm_02 = "rgba(10, 13, 18, 0.10000000149011612)"
                public static let shadow_md_01 = "rgba(10, 13, 18, 0.10000000149011612)"
                public static let shadow_md_02 = "rgba(10, 13, 18, 0.05999999865889549)"
                public static let shadow_lg_01 = "rgba(10, 13, 18, 0.07999999821186066)"
                public static let shadow_lg_02 = "rgba(10, 13, 18, 0.029999999329447746)"
                public static let shadow_lg_03 = "rgba(10, 13, 18, 0.03999999910593033)"
                public static let shadow_xl_01 = "rgba(10, 13, 18, 0.07999999821186066)"
                public static let shadow_xl_02 = "rgba(10, 13, 18, 0.029999999329447746)"
                public static let shadow_xl_03 = "rgba(10, 13, 18, 0.03999999910593033)"
                public static let shadow_2xl_01 = "rgba(10, 13, 18, 0.18000000715255737)"
                public static let shadow_2xl_02 = "rgba(10, 13, 18, 0.03999999910593033)"
                public static let shadow_3xl_01 = "rgba(10, 13, 18, 0.14000000059604645)"
                public static let shadow_3xl_02 = "rgba(10, 13, 18, 0.03999999910593033)"
                public static let shadow_skeumorphic_inner = "rgba(10, 13, 18, 0.05000000074505806)"
                public static let shadow_skeumorphic_inner_border = "rgba(10, 13, 18, 0.18000000715255737)"
            }
            public enum Portfolio {
                public enum mockups {
                    public static let shadow_main_centre_md = "rgba(10, 13, 18, 0.14000000059604645)"
                    public static let shadow_main_centre_lg = "rgba(10, 13, 18, 0.18000000715255737)"
                    public static let shadow_overlay_lg = "rgba(10, 13, 18, 0.11999999731779099)"
                    public static let shadow_grid_md = "rgba(10, 13, 18, 0.07999999821186066)"
                }
            }
        }
    }
    public enum Spacing {
        public enum _0 {
            public static let _0px_ = "0px"
        }
        public enum _1 {
            public static let _4px_ = "4px"
        }
        public enum _2 {
            public static let _8px_ = "8px"
        }
        public enum _3 {
            public static let _12px_ = "12px"
        }
        public enum _4 {
            public static let _16px_ = "16px"
        }
        public enum _5 {
            public static let _20px_ = "20px"
        }
        public enum _6 {
            public static let _24px_ = "24px"
        }
        public enum _8 {
            public static let _32px_ = "32px"
        }
        public enum _10 {
            public static let _40px_ = "40px"
        }
        public enum _12 {
            public static let _48px_ = "48px"
        }
        public enum _16 {
            public static let _64px_ = "64px"
        }
        public enum _20 {
            public static let _80px_ = "80px"
        }
        public enum _24 {
            public static let _96px_ = "96px"
        }
        public enum _32 {
            public static let _128px_ = "128px"
        }
        public enum _40 {
            public static let _160px_ = "160px"
        }
        public enum _48 {
            public static let _192px_ = "192px"
        }
        public enum _56 {
            public static let _224px_ = "224px"
        }
        public enum _64 {
            public static let _256px_ = "256px"
        }
        public enum _80 {
            public static let _320px_ = "320px"
        }
        public enum _96 {
            public static let _384px_ = "384px"
        }
        public enum _120 {
            public static let _480px_ = "480px"
        }
        public enum _140 {
            public static let _560px_ = "560px"
        }
        public enum _160 {
            public static let _640px_ = "640px"
        }
        public enum _180 {
            public static let _720px_ = "720px"
        }
        public enum _192 {
            public static let _768px_ = "768px"
        }
        public enum _256 {
            public static let _1_024px_ = "1024px"
        }
        public enum _320 {
            public static let _1_280px_ = "1280px"
        }
        public enum _360 {
            public static let _1_440px_ = "1440px"
        }
        public enum _400 {
            public static let _1_600px_ = "1600px"
        }
        public enum _480 {
            public static let _1_920px_ = "1920px"
        }
        public enum _0_5 {
            public static let _2px_ = "2px"
        }
        public enum _1_5 {
            public static let _6px_ = "6px"
        }
    }
    public enum Width {
        public enum MOVE {
            public static let width_lg = "1024px"
            public static let width_md = "768px"
        }
    }
    public enum Component {
        public enum colors {
            public enum Alpha {
                public static let alpha_white_10 = "rgba(255, 255, 255, 0.10000000149011612)"
                public static let alpha_white_20 = "rgba(255, 255, 255, 0.20000000298023224)"
                public static let alpha_white_30 = "rgba(255, 255, 255, 0.30000001192092896)"
                public static let alpha_white_40 = "rgba(255, 255, 255, 0.4000000059604645)"
                public static let alpha_white_50 = "rgba(255, 255, 255, 0.5)"
                public static let alpha_white_60 = "rgba(255, 255, 255, 0.6000000238418579)"
                public static let alpha_white_70 = "rgba(255, 255, 255, 0.699999988079071)"
                public static let alpha_white_80 = "rgba(255, 255, 255, 0.800000011920929)"
                public static let alpha_white_90 = "rgba(255, 255, 255, 0.8999999761581421)"
                public static let alpha_white_100 = "rgba(255, 255, 255, 1)"
                public static let alpha_black_10 = "rgba(0, 0, 0, 0.10000000149011612)"
                public static let alpha_black_20 = "rgba(0, 0, 0, 0.20000000298023224)"
                public static let alpha_black_30 = "rgba(0, 0, 0, 0.30000001192092896)"
                public static let alpha_black_40 = "rgba(0, 0, 0, 0.4000000059604645)"
                public static let alpha_black_50 = "rgba(0, 0, 0, 0.5)"
                public static let alpha_black_60 = "rgba(0, 0, 0, 0.6000000238418579)"
                public static let alpha_black_70 = "rgba(0, 0, 0, 0.699999988079071)"
                public static let alpha_black_80 = "rgba(0, 0, 0, 0.800000011920929)"
                public static let alpha_black_90 = "rgba(0, 0, 0, 0.8999999761581421)"
                public static let alpha_black_100 = "rgba(0, 0, 0, 1)"
            }
            public enum Utility {
                public enum Gray {
                    public static let utility_gray_50 = "rgba(247, 246, 245, 1)"
                    public static let utility_gray_100 = "rgba(240, 239, 237, 1)"
                    public static let utility_gray_200 = "rgba(228, 227, 225, 1)"
                    public static let utility_gray_300 = "rgba(215, 211, 208, 1)"
                    public static let utility_gray_400 = "rgba(169, 162, 157, 1)"
                    public static let utility_gray_500 = "rgba(121, 113, 107, 1)"
                    public static let utility_gray_600 = "rgba(87, 83, 78, 1)"
                    public static let utility_gray_700 = "rgba(68, 64, 60, 1)"
                    public static let utility_gray_800 = "rgba(41, 37, 36, 1)"
                    public static let utility_gray_900 = "rgba(21, 21, 21, 1)"
                    public enum blue {
                        public static let utility_gray_blue_50 = "rgba(248, 249, 252, 1)"
                        public static let utility_gray_blue_100 = "rgba(234, 236, 245, 1)"
                        public static let utility_gray_blue_200 = "rgba(213, 217, 235, 1)"
                        public static let utility_gray_blue_300 = "rgba(179, 184, 219, 1)"
                        public static let utility_gray_blue_400 = "rgba(113, 123, 188, 1)"
                        public static let utility_gray_blue_500 = "rgba(78, 91, 166, 1)"
                        public static let utility_gray_blue_600 = "rgba(62, 71, 132, 1)"
                        public static let utility_gray_blue_700 = "rgba(54, 63, 114, 1)"
                    }
                }
                public enum Brand {
                    public static let utility_brand_50 = "rgba(254, 244, 240, 1)"
                    public static let utility_brand_50_alt = "rgba(254, 244, 240, 1)"
                    public static let utility_brand_100 = "rgba(253, 224, 214, 1)"
                    public static let utility_brand_100_alt = "rgba(253, 224, 214, 1)"
                    public static let utility_brand_200 = "rgba(250, 194, 173, 1)"
                    public static let utility_brand_200_alt = "rgba(250, 194, 173, 1)"
                    public static let utility_brand_300 = "rgba(248, 163, 133, 1)"
                    public static let utility_brand_300_alt = "rgba(248, 163, 133, 1)"
                    public static let utility_brand_400 = "rgba(247, 133, 92, 1)"
                    public static let utility_brand_400_alt = "rgba(247, 133, 92, 1)"
                    public static let utility_brand_500 = "rgba(246, 117, 71, 1)"
                    public static let utility_brand_500_alt = "rgba(246, 117, 71, 1)"
                    public static let utility_brand_600 = "rgba(243, 102, 51, 1)"
                    public static let utility_brand_600_alt = "rgba(243, 102, 51, 1)"
                    public static let utility_brand_700 = "rgba(220, 62, 5, 1)"
                    public static let utility_brand_700_alt = "rgba(220, 62, 5, 1)"
                    public static let utility_brand_800 = "rgba(195, 55, 4, 1)"
                    public static let utility_brand_800_alt = "rgba(195, 55, 4, 1)"
                    public static let utility_brand_900 = "rgba(165, 50, 8, 1)"
                    public static let utility_brand_900_alt = "rgba(165, 50, 8, 1)"
                }
                public enum Error {
                    public static let utility_error_50 = "rgba(254, 243, 242, 1)"
                    public static let utility_error_100 = "rgba(254, 228, 226, 1)"
                    public static let utility_error_200 = "rgba(254, 205, 202, 1)"
                    public static let utility_error_300 = "rgba(253, 162, 155, 1)"
                    public static let utility_error_400 = "rgba(249, 112, 102, 1)"
                    public static let utility_error_500 = "rgba(240, 68, 56, 1)"
                    public static let utility_error_600 = "rgba(200, 54, 41, 1)"
                    public static let utility_error_700 = "rgba(180, 35, 24, 1)"
                }
                public enum Warning {
                    public static let utility_warning_50 = "rgba(255, 250, 235, 1)"
                    public static let utility_warning_100 = "rgba(254, 240, 199, 1)"
                    public static let utility_warning_200 = "rgba(254, 223, 137, 1)"
                    public static let utility_warning_300 = "rgba(254, 200, 75, 1)"
                    public static let utility_warning_400 = "rgba(255, 199, 9, 1)"
                    public static let utility_warning_500 = "rgba(255, 199, 9, 1)"
                    public static let utility_warning_600 = "rgba(255, 199, 9, 1)"
                    public static let utility_warning_700 = "rgba(255, 199, 9, 1)"
                }
                public enum Success {
                    public static let utility_success_50 = "rgba(236, 253, 243, 1)"
                    public static let utility_success_100 = "rgba(220, 250, 230, 1)"
                    public static let utility_success_200 = "rgba(171, 239, 198, 1)"
                    public static let utility_success_300 = "rgba(117, 224, 167, 1)"
                    public static let utility_success_400 = "rgba(71, 205, 137, 1)"
                    public static let utility_success_500 = "rgba(23, 178, 106, 1)"
                    public static let utility_success_600 = "rgba(68, 132, 34, 1)"
                    public static let utility_success_700 = "rgba(6, 118, 71, 1)"
                }
                public enum Green {
                    public static let utility_green_50 = "rgba(237, 252, 242, 1)"
                    public static let utility_green_100 = "rgba(211, 248, 223, 1)"
                    public static let utility_green_200 = "rgba(170, 240, 196, 1)"
                    public static let utility_green_300 = "rgba(115, 226, 163, 1)"
                    public static let utility_green_400 = "rgba(60, 203, 127, 1)"
                    public static let utility_green_500 = "rgba(22, 179, 100, 1)"
                    public static let utility_green_600 = "rgba(9, 146, 80, 1)"
                    public static let utility_green_700 = "rgba(8, 116, 67, 1)"
                }
                public enum Blue {
                    public enum light {
                        public static let utility_blue_light_50 = "rgba(240, 249, 255, 1)"
                        public static let utility_blue_light_100 = "rgba(224, 242, 254, 1)"
                        public static let utility_blue_light_200 = "rgba(185, 230, 254, 1)"
                        public static let utility_blue_light_300 = "rgba(124, 212, 253, 1)"
                        public static let utility_blue_light_400 = "rgba(54, 191, 250, 1)"
                        public static let utility_blue_light_500 = "rgba(11, 165, 236, 1)"
                        public static let utility_blue_light_600 = "rgba(0, 134, 201, 1)"
                        public static let utility_blue_light_700 = "rgba(2, 106, 162, 1)"
                    }
                    public static let utility_blue_50 = "rgba(239, 248, 255, 1)"
                    public static let utility_blue_100 = "rgba(209, 233, 255, 1)"
                    public static let utility_blue_200 = "rgba(178, 221, 255, 1)"
                    public static let utility_blue_300 = "rgba(132, 202, 255, 1)"
                    public static let utility_blue_400 = "rgba(83, 177, 253, 1)"
                    public static let utility_blue_500 = "rgba(46, 144, 250, 1)"
                    public static let utility_blue_600 = "rgba(21, 112, 239, 1)"
                    public static let utility_blue_700 = "rgba(23, 92, 211, 1)"
                    public enum dark {
                        public static let utility_blue_dark_50 = "rgba(239, 244, 255, 1)"
                        public static let utility_blue_dark_100 = "rgba(209, 224, 255, 1)"
                        public static let utility_blue_dark_200 = "rgba(178, 204, 255, 1)"
                        public static let utility_blue_dark_300 = "rgba(132, 173, 255, 1)"
                        public static let utility_blue_dark_400 = "rgba(82, 139, 255, 1)"
                        public static let utility_blue_dark_500 = "rgba(41, 112, 255, 1)"
                        public static let utility_blue_dark_600 = "rgba(21, 94, 239, 1)"
                        public static let utility_blue_dark_700 = "rgba(0, 78, 235, 1)"
                    }
                }
                public enum Indigo {
                    public static let utility_indigo_50 = "rgba(238, 244, 255, 1)"
                    public static let utility_indigo_100 = "rgba(224, 234, 255, 1)"
                    public static let utility_indigo_200 = "rgba(199, 215, 254, 1)"
                    public static let utility_indigo_300 = "rgba(164, 188, 253, 1)"
                    public static let utility_indigo_400 = "rgba(128, 152, 249, 1)"
                    public static let utility_indigo_500 = "rgba(97, 114, 243, 1)"
                    public static let utility_indigo_600 = "rgba(68, 76, 231, 1)"
                    public static let utility_indigo_700 = "rgba(53, 56, 205, 1)"
                }
                public enum Purple {
                    public static let utility_purple_50 = "rgba(244, 243, 255, 1)"
                    public static let utility_purple_100 = "rgba(235, 233, 254, 1)"
                    public static let utility_purple_200 = "rgba(217, 214, 254, 1)"
                    public static let utility_purple_300 = "rgba(189, 180, 254, 1)"
                    public static let utility_purple_400 = "rgba(155, 138, 251, 1)"
                    public static let utility_purple_500 = "rgba(122, 90, 248, 1)"
                    public static let utility_purple_600 = "rgba(105, 56, 239, 1)"
                    public static let utility_purple_700 = "rgba(89, 37, 220, 1)"
                }
                public enum Fuchsia {
                    public static let utility_fuchsia_50 = "rgba(253, 244, 255, 1)"
                    public static let utility_fuchsia_100 = "rgba(251, 232, 255, 1)"
                    public static let utility_fuchsia_200 = "rgba(246, 208, 254, 1)"
                    public static let utility_fuchsia_300 = "rgba(238, 170, 253, 1)"
                    public static let utility_fuchsia_400 = "rgba(228, 120, 250, 1)"
                    public static let utility_fuchsia_500 = "rgba(212, 68, 241, 1)"
                    public static let utility_fuchsia_600 = "rgba(186, 36, 213, 1)"
                    public static let utility_fuchsia_700 = "rgba(159, 26, 177, 1)"
                }
                public enum Pink {
                    public static let utility_pink_50 = "rgba(253, 242, 250, 1)"
                    public static let utility_pink_100 = "rgba(252, 231, 246, 1)"
                    public static let utility_pink_200 = "rgba(252, 206, 238, 1)"
                    public static let utility_pink_300 = "rgba(250, 167, 224, 1)"
                    public static let utility_pink_400 = "rgba(246, 112, 199, 1)"
                    public static let utility_pink_500 = "rgba(238, 70, 188, 1)"
                    public static let utility_pink_600 = "rgba(221, 37, 144, 1)"
                    public static let utility_pink_700 = "rgba(193, 21, 116, 1)"
                }
                public enum Orange {
                    public enum dark {
                        public static let utility_orange_dark_50 = "rgba(255, 244, 237, 1)"
                        public static let utility_orange_dark_100 = "rgba(255, 230, 213, 1)"
                        public static let utility_orange_dark_200 = "rgba(255, 214, 174, 1)"
                        public static let utility_orange_dark_300 = "rgba(255, 156, 102, 1)"
                        public static let utility_orange_dark_400 = "rgba(255, 105, 46, 1)"
                        public static let utility_orange_dark_500 = "rgba(255, 68, 5, 1)"
                        public static let utility_orange_dark_600 = "rgba(230, 46, 5, 1)"
                        public static let utility_orange_dark_700 = "rgba(188, 27, 6, 1)"
                    }
                    public static let utility_orange_50 = "rgba(254, 246, 238, 1)"
                    public static let utility_orange_100 = "rgba(253, 234, 215, 1)"
                    public static let utility_orange_200 = "rgba(249, 219, 175, 1)"
                    public static let utility_orange_300 = "rgba(247, 178, 122, 1)"
                    public static let utility_orange_400 = "rgba(243, 135, 68, 1)"
                    public static let utility_orange_500 = "rgba(239, 104, 32, 1)"
                    public static let utility_orange_600 = "rgba(224, 79, 22, 1)"
                    public static let utility_orange_700 = "rgba(185, 56, 21, 1)"
                }
                public enum Yellow {
                    public static let utility_yellow_50 = "rgba(254, 251, 232, 1)"
                    public static let utility_yellow_100 = "rgba(254, 247, 195, 1)"
                    public static let utility_yellow_200 = "rgba(254, 238, 149, 1)"
                    public static let utility_yellow_300 = "rgba(253, 226, 114, 1)"
                    public static let utility_yellow_400 = "rgba(250, 197, 21, 1)"
                    public static let utility_yellow_500 = "rgba(234, 170, 8, 1)"
                    public static let utility_yellow_600 = "rgba(202, 133, 4, 1)"
                    public static let utility_yellow_700 = "rgba(161, 92, 7, 1)"
                }
            }
            public enum Components {
                public enum App {
                    public enum store {
                        public enum badges {
                            public static let app_store_badge_border = "rgba(166, 166, 166, 1)"
                        }
                    }
                }
                public enum Avatars {
                    public static let avatar_styles_bg_neutral = "rgba(224, 224, 224, 1)"
                }
                public enum Buttons {
                    public static let button_primary_icon = "rgba(253, 224, 214, 1)"
                    public static let button_primary_icon_hover = "rgba(250, 194, 173, 1)"
                    public static let button_destructive_primary_icon = "rgba(253, 162, 155, 1)"
                    public static let button_destructive_primary_icon_hover = "rgba(254, 205, 202, 1)"
                    public enum Primary {
                        public static let button_primary_fg = "rgba(255, 255, 255, 1)"
                        public static let button_primary_bg = "rgba(243, 102, 51, 1)"
                        public static let button_primary_border = "rgba(255, 255, 255, 0.11999999731779099)"
                    }
                    public enum Secondary {
                        public static let button_secondary_fg = "rgba(68, 64, 60, 1)"
                    }
                    public enum Tertiary {
                        public enum color {
                            public static let button_tertiary_color_fg = "rgba(220, 62, 5, 1)"
                        }
                        public enum error {
                            public static let button_tertiary_error_fg = "rgba(180, 35, 24, 1)"
                        }
                    }
                }
                public enum Footers {
                    public static let footer_button_fg = "rgba(250, 194, 173, 1)"
                    public static let footer_button_fg_hover = "rgba(255, 255, 255, 1)"
                }
                public enum Icons {
                    public enum Icons {
                        public static let icon_fg_brand = "rgba(243, 102, 51, 1)"
                        public static let icon_fg_brand_on_brand = "rgba(250, 194, 173, 1)"
                    }
                    public enum Featured {
                        public enum icons {
                            public static let featured_icon_light_fg_brand = "rgba(243, 102, 51, 1)"
                            public static let featured_icon_light_fg_gray = "rgba(121, 113, 107, 1)"
                            public static let featured_icon_light_fg_error = "rgba(200, 54, 41, 1)"
                            public static let featured_icon_light_fg_warning = "rgba(255, 199, 9, 1)"
                            public static let featured_icon_light_fg_success = "rgba(68, 132, 34, 1)"
                            public enum Dark {
                                public static let featured_icon_dark_fg_brand = "rgba(255, 255, 255, 1)"
                            }
                        }
                    }
                }
                public enum Mockups {
                    public static let screen_mockup_border = "rgba(21, 21, 21, 1)"
                }
                public enum Sliders {
                    public static let slider_handle_bg = "rgba(255, 255, 255, 1)"
                    public static let slider_handle_border = "rgba(243, 102, 51, 1)"
                }
                public enum Toggles {
                    public static let toggle_button_fg_disabled = "rgba(247, 246, 245, 1)"
                    public static let toggle_border = "rgba(215, 211, 208, 1)"
                    public static let toggle_slim_border_pressed = "rgba(243, 102, 51, 1)"
                    public static let toggle_slim_border_pressed_hover = "rgba(220, 62, 5, 1)"
                }
                public enum Tooltips {
                    public static let tooltip_supporting_text = "rgba(215, 211, 208, 1)"
                }
                public enum Text {
                    public enum editor {
                        public static let text_editor_icon_fg = "rgba(169, 162, 157, 1)"
                        public static let text_editor_icon_fg_active = "rgba(121, 113, 107, 1)"
                    }
                }
                public enum Header {
                    public enum sections {
                        public enum Brand {
                            public enum header {
                                public static let ____header_brand_text_secondary = "rgba(250, 194, 173, 1)"
                            }
                        }
                    }
                }
            }
        }
    }
    public static let container_padding_mobile = "16px"
    public static let container_padding_desktop = "32px"
    public static let container_max_width_desktop = "1280px"
    public enum Approach {
        public enum _2 {
            public static let container_max_width = "1280px"
        }
    }
    public static let width_xxs = "320px"
    public static let width_xs = "384px"
    public static let width_sm = "480px"
    public static let width_md = "560px"
    public static let width_lg = "640px"
    public static let width_xl = "768px"
    public static let width_2xl = "1024px"
    public static let width_3xl = "1280px"
    public static let width_4xl = "1440px"
    public static let width_5xl = "1600px"
    public static let width_6xl = "1920px"
    public static let paragraph_max_width = "720px"
    public static let spacing_none = "0px"
    public static let spacing_xxs = "2px"
    public static let spacing_xs = "4px"
    public static let spacing_sm = "6px"
    public static let spacing_md = "8px"
    public static let spacing_lg = "12px"
    public static let spacing_xl = "16px"
    public static let spacing_2xl = "20px"
    public static let spacing_3xl = "24px"
    public static let spacing_4xl = "32px"
    public static let spacing_5xl = "40px"
    public static let spacing_6xl = "48px"
    public static let spacing_7xl = "64px"
    public static let spacing_8xl = "80px"
    public static let spacing_9xl = "96px"
    public static let spacing_10xl = "128px"
    public static let spacing_11xl = "160px"
    public static let radius_none = 0
    public static let radius_xxs = 2
    public static let radius_xs = 4
    public static let radius_sm = 6
    public static let radius_md = 8
    public static let radius_lg = 10
    public static let radius_xl = 12
    public static let radius_2xl = 16
    public static let radius_3xl = 20
    public static let radius_4xl = 24
    public static let radius_full = 9999
    public enum Font {
        public enum family {
            public static let font_family_display = "GSK Precision"
            public static let font_family_body = "Arial"
        }
        public enum weight {
            public static let regular = "Regular"
            public static let regular_italic = "Italic"
            public static let medium = "Regular"
            public static let medium_italic = "Italic"
            public static let semibold = "Regular"
            public static let semibold_italic = "Italic"
            public static let bold = "Bold"
            public static let bold_italic = "Bold Italic"
        }
        public enum size {
            public static let text_3xs = "8px"
            public static let text_2xs = "10px"
            public static let text_xs = "12px"
            public static let text_sm = "14px"
            public static let text_md = "16px"
            public static let text_lg = "18px"
            public static let text_xl = "20px"
            public static let display_xs = "24px"
            public static let display_sm = "30px"
            public static let display_md = "36px"
            public static let display_lg = "48px"
            public static let display_xl = "60px"
            public static let display_2xl = "72px"
        }
    }
    public enum Line {
        public enum height {
            public static let text_3xs = "10px"
            public static let text_2xs = "12px"
            public static let text_xs = "18px"
            public static let text_sm = "20px"
            public static let text_md = "24px"
            public static let text_lg = "28px"
            public static let text_xl = "30px"
            public static let display_xs = "32px"
            public static let display_sm = "38px"
            public static let display_md = "44px"
            public static let display_lg = "60px"
            public static let display_xl = "72px"
            public static let display_2xl = "90px"
        }
    }

}
