// swiftui-tokens.js
export default function ({ dictionary }) {
  const swiftKeywords = new Set([
    "true", "false", "nil", "class", "struct", "enum",
    "protocol", "extension", "import", "let", "var", "func"
  ]);

  // Sanitize token names for Swift
  function sanitize(name) {
    if (typeof name !== "string") {
      if (name == null) return "_token";
      if (typeof name === "boolean" || typeof name === "number") {
        name = String(name);
      } else {
        return "_token";
      }
    }

    name = name.trim();
    let safe = name.replace(/[^A-Za-z0-9_]/g, "_");
    if (/^[0-9]/.test(safe)) safe = `_${safe}`;
    if (safe.length === 0) safe = "_token";
    if (swiftKeywords.has(safe)) safe = `${safe}_token`;

    return safe;
  }

  // Convert token value to SwiftUI representation
    const convertValue = (token) => {
      const value = token.$value;

      if (typeof value === "object" && value !== null && "r" in value) {
        const r = Number(value.r).toFixed(3);
        const g = Number(value.g).toFixed(3);
        const b = Number(value.b).toFixed(3);
        const a = Number(value.a ?? 1).toFixed(3);
        return `Color(red: ${r}, green: ${g}, blue: ${b}, opacity: ${a})`;
      }

        if (typeof value === "string" && value.startsWith("#")) {
            // Convert hex to RGB
            const hex = value.replace("#", "");
            const r = parseInt(hex.substring(0,2), 16) / 255;
            const g = parseInt(hex.substring(2,4), 16) / 255;
            const b = parseInt(hex.substring(4,6), 16) / 255;
            return `Color(red: ${r.toFixed(3)}, green: ${g.toFixed(3)}, blue: ${b.toFixed(3)}, opacity: 1.000)`;
        }

      if (typeof value === "boolean") return value ? "true" : "false";
      if (!isNaN(value)) return `${value}`;

      return `"${value}"`;
    };


  // Detect leaf token
  function isToken(node) {
    return node && typeof node === "object" && ("$value" in node || "value" in node);
  }

  // Recursive Swift enum builder
  function buildEnum(node, indent = 1) {
    const pad = "    ".repeat(indent);
    let out = "";

    Object.entries(node).forEach(([key, value]) => {
      const safeKey = sanitize(key);

      if (isToken(value)) {
        if (!value.name) value.name = key;
        out += `${pad}public static let ${safeKey} = ${convertValue(value)}\n`;
      } else if (typeof value === "object" && value !== null) {
        out += `${pad}public enum ${safeKey} {\n`;
        out += buildEnum(value, indent + 1);
        out += `${pad}}\n`;
      }
    });

    return out;
  }

  const root = dictionary.tokens;

  return `//
// SwiftUI Tokens – Auto generated by Style Dictionary
//

import SwiftUI

public enum DesignTokens {
${buildEnum(root, 1)}
}
`;
}
